orbs:
  gke: circleci/gcp-gke@1.1.0
  helm: circleci/helm@1.1.2
  kubernetes: circleci/kubernetes@0.11.2
version: 2.1
jobs:
  containerization:
    machine: true

    steps:
      - checkout
      - run: |
          echo "$dockerhub_pass" | docker login --username zarakmughal --password-stdin

      - run: docker build -t zarakmughal/goapp-cicd:main .

      - run: docker push zarakmughal/goapp-cicd:main

  update-kubeconfig:
    machine: true
    description: >
      Allows the kubectl client to work with a GKE cluster. Updates the kubectl
      configuration file with GKE cluster access credentials.
    parameters:
      cluster:
        description: |
          The name of the cluster for which to create a kubeconfig entry.
        type: string
      install-kubectl:
        default: false
        description: |
          Whether to install kubectl
        type: boolean
    steps:
      - when:
          condition: <<parameters.install-kubectl>>
          steps:
            - kubernetes/install-kubectl
      - run:
          command: |
            gcloud container clusters get-credentials <<parameters.cluster>>
          name: Update kubeconfig with cluster credentials

  deploy:
    machine: true
    steps:
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - gke/create-cluster:
          additional-args: "--cluster-version=1.16 --enable-ip-alias --num-nodes=1"
          cluster: goapp
          install-kubectl: true
      - gke/create-node-pool:
          additional-args: >-
            --image-type=cos --machine-type=e2-small --num-nodes=1
          cluster: goapp
          node-pool: goapp-node
  check:
    machine: true
    steps:
      - run: kubectl
  # helm:
  #   machine: true
  #   steps:
  #     - install-helm-on-cluster:
  #         cluster-name: goapp


workflows:
  test:
    jobs:
      - update-kubeconfig:
          cluster: "goapp"
          install-kubectl: true
      - check
      # - containerization
      # - deploy
      # # - helm