version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout
      - run: |
         echo "$dockerhub_pass" | docker login --username zarakmughal --password-stdin

      # build the application image
      - run: docker build -t zarakmughal/goapp-cicd:main .

      # deploy the image
      - run: docker push zarakmughal/goapp-cicd:$TAG

