version: 2
jobs:
  build:
    docker:
      - image: zarakmughal/goapp-cicd
        auth:
          username: zarakmughal
          password: $dockerhub_pass

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t zarakmughal/goapp-cicd:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push zarakmughal/goapp-cicd:$TAG

