version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout
      - run: |
         echo "$dockerhub_pass" | docker login --username zarakmughal --password-stdin

      # build the application image
      - run: |
        TAG=0.1.$CIRCLE_BUILD_NUM
        docker build -t zarakmughal/goapp-cicd:$TAG .

      # deploy the image
      - run: docker push zarakmughal/goapp-cicd:$TAG

