orbs:
  gcp-gke: circleci/gcp-gke@1.1.0
version: 2.1
workflows:
  main:
    jobs:    
      - gke/create-cluster:
          additional-args: '--cluster-version=1.16 --enable-ip-alias --num-nodes=1'
          cluster: gcp-testing
      - gke/create-node-pool:
          additional-args: >-
            --image-type=cos --no-enable-autoupgrade
            --machine-type=e2-small --num-nodes=2
          cluster: gcp-testing
          node-pool: goapp-node-pool
          requires:
            - gke/create-cluster          